#include "mapping.hpp"

//?Angezeigte Daten
    map<string, string> exiftoUser = {
        {"Exif.Image.Make", "Hersteller"},
        {"Exif.Image.Model", "Kameramodell"},
        {"Exif.Image.Orientation", "Orientierung"},
        {"Exif.Image.XResolution", "X Aufloesung"},
        {"Exif.Image.YResolution", "Y Aufloesung"},
        {"Exif.Image.ResolutionUnit", "Aufloesungseinheit"},
        {"Exif.Image.Software", "Software"},
        {"Exif.Image.DateTime", "Datum"},
        {"Exif.Image.YCbCrPositioning", "YCbCr Positionierung"},
        {"Exif.Image.ExifTag", "EXIF Tag"},
        {"Exif.Photo.0x0100", "Bildbreite"},
        {"Exif.Photo.0x0101", "Bildhoehe"},
        {"Exif.Photo.ExposureTime", "Belichtungszeit"},
        {"Exif.Photo.FNumber", "Blende"},
        {"Exif.Photo.ExposureProgram", "Belichtungsprogramm"},
        {"Exif.Photo.ISOSpeedRatings", "ISO"},
        {"Exif.Photo.ExifVersion", "EXIF Version"},
        {"Exif.Photo.DateTimeOriginal", "Aufnahmedatum"},
        {"Exif.Photo.DateTimeDigitized", "Digitalisiert"},
        {"Exif.Photo.ComponentsConfiguration", "Komponenten"},
        {"Exif.Photo.ShutterSpeedValue", "Verschlusszeit"},
        {"Exif.Photo.ApertureValue", "Blendenwert"},
        {"Exif.Photo.BrightnessValue", "Helligkeit"},
        {"Exif.Photo.ExposureBiasValue", "Belichtungskorrektur"},
        {"Exif.Photo.MaxApertureValue", "Max Blende"},
        {"Exif.Photo.MeteringMode", "Messmodus"},
        {"Exif.Photo.Flash", "Blitz"},
        {"Exif.Photo.FocalLength", "Brennweite"},
        {"Exif.Photo.SubSecTime", "Millisekunden"},
        {"Exif.Photo.SubSecTimeOriginal", "Original Millisekunden"},
        {"Exif.Photo.SubSecTimeDigitized", "Digitalisiert Millisekunden"},
        {"Exif.Photo.ColorSpace", "Farbraum"},
        {"Exif.Photo.WhiteBalance", "Weissabgleich"},
        {"Exif.Photo.FocalLengthIn35mmFilm", "35mm Brennweite"},
        {"Exif.Photo.SceneCaptureType", "Szenentyp"},
        {"Exif.Photo.ImageUniqueID", "Bild ID"},
        {"Exif.Photo.InteroperabilityTag", "Interoperabilität Tag"},
        {"Exif.Iop.InteroperabilityIndex", "Interoperabilität Index"},
        {"Exif.Iop.InteroperabilityVersion", "Interobilität Version"},
        {"Exif.Photo.SensingMethod", "Abtastverfahren"},
        {"Exif.Photo.SceneType", "Szenentyp"},
        {"Exif.Photo.ExposureMode", "Belichtungsmodus"}
    };

    //?Eingegebene Daten
    map<string, string> userToExif = {
        {"hersteller", "Exif.Image.Make"},
        {"kameramodell", "Exif.Image.Model"},
        {"orientierung", "Exif.Image.Orientation"},
        {"xaufloesung", "Exif.Image.XResolution"},
        {"yaufloesung", "Exif.Image.YResolution"},
        {"aufloesungseinheit", "Exif.Image.ResolutionUnit"},
        {"software", "Exif.Image.Software"},
        {"datum", "Exif.Image.DateTime"},
        {"ycbcr positionierung", "Exif.Image.YCbCrPositioning"},
        {"exif tag", "Exif.Image.ExifTag"},
        {"bildbreite", "Exif.Photo.ImageLength"},
        {"bildhoehe", "Exif.Photo.ImageWidth"},
        {"belichtungszeit", "Exif.Photo.ExposureTime"},
        {"blende", "Exif.Photo.FNumber"},
        {"belichtungsprogramm", "Exif.Photo.ExposureProgram"},
        {"iso", "Exif.Photo.ISOSpeedRatings"},
        {"exif version", "Exif.Photo.ExifVersion"},
        {"aufnahmedatum", "Exif.Photo.DateTimeOriginal"},
        {"digitalisiert", "Exif.Photo.DateTimeDigitized"},
        {"komponenten", "Exif.Photo.ComponentsConfiguration"},
        {"verschlusszeit", "Exif.Photo.ShutterSpeedValue"},
        {"blendenwert", "Exif.Photo.ApertureValue"},
        {"helligkeit", "Exif.Photo.BrightnessValue"},
        {"belichtungskorrektur", "Exif.Photo.ExposureBiasValue"},
        {"maxblende", "Exif.Photo.MaxApertureValue"},
        {"messmodus", "Exif.Photo.MeteringMode"},
        {"blitz", "Exif.Photo.Flash"},
        {"brennweite", "Exif.Photo.FocalLength"},
        {"millisekunden", "Exif.Photo.SubSecTime"},
        {"originalmillisekunden", "Exif.Photo.SubSecTimeOriginal"},
        {"digitalisiert millisekunden", "Exif.Photo.SubSecTimeDigitized"},
        {"farbraum", "Exif.Photo.ColorSpace"},
        {"weissabgleich", "Exif.Photo.WhiteBalance"},
        {"35mmbrennweite", "Exif.Photo.FocalLengthIn35mmFilm"},
        {"szenentyp", "Exif.Photo.SceneCaptureType"},
        {"bildid", "Exif.Photo.ImageUniqueID"},
        {"Szenentyp", "Exif.Photo.SceneCaptureType"},
        {"Bild ID", "Exif.Photo.ImageUniqueID"},
        {"Interoperabilität Tag", "Exif.Photo.InteroperabilityTag"},
        {"Interoperabilität Index", "Exif.Iop.InteroperabilityIndex"},
        {"Interobilität Version", "Exif.Iop.InteroperabilityVersion"},
        {"Abtastverfahren", "Exif.Photo.SensingMethod"},
        {"Szenentyp", "Exif.Photo.SceneType"},
        {"Belichtungsmodus", "Exif.Photo.ExposureMode"}
    };

    //?Daten zum Validierung
    map<string, string> fieldType = {
        {"Exif.Image.Orientation", "digit"},
        {"Exif.Image.DateTime", "date"},
        {"Exif.Image.ExifTag", "digit"},
        {"Exif.Photo.0x0100", "digit"},
        {"Exif.Photo.0x0101", "digit"},
        {"Exif.Photo.ISOSpeedRatings", "digit"},
        {"Exif.Photo.DateTimeOriginal", "date"},
        {"Exif.Photo.DateTimeDigitized", "date"},
        {"Exif.Photo.SubSecTime", "digit"},
        {"Exif.Photo.SubSecTimeOriginal", "digit"},
        {"Exif.Photo.SubSecTimeDigitized", "digit"},
        {"Exif.Photo.ColorSpace", "digit"},
    };
